# Generated by Django 3.0.2 on 2020-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Фото')),
                ('option', models.CharField(choices=[('moscow_detail', 'москвич'), ('sliva_detail', 'слива'), ('volga_detail', 'волга')], max_length=20, verbose_name='Категория')),
            ],
        ),
    ]
